name: Example App CI

on:
  pull_request:
    paths:
      - 'example/**'
      - '.github/workflows/example_app_ci.yml'

      # --- Shared paths for BOTH workflows ---
      - 'package.json'
      - 'yarn.lock'
      - '.eslintrc.js'
      - '.prettierrc.json'
      - 'tsconfig.base.json'
  push:
    branches:
      - main
    paths:
      - 'example/**'
      - '.github/workflows/example-app-ci.yml'

      # --- Shared paths for BOTH workflows ---
      - 'package.json'
      - 'yarn.lock'
      - '.eslintrc.js'
      - '.prettierrc.json'
      - 'tsconfig.base.json'

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: 📦 Install Yarn
        run: npm install -g yarn

      - name: 🌿 Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: 📦 Install root dependencies
        run: yarn install --frozen-lockfile

      - name: 📦 Install example dependencies (and build SDK)
        run: yarn install --frozen-lockfile
        working-directory: ./example

      - name: 🤓 Run ESLint
        run: yarn lint
        working-directory: ./example

      - name: ✨ Run Prettier check
        run: yarn prettier:check
        working-directory: ./example

      - name: 🔍 Run TypeScript check
        run: yarn ts:check
        working-directory: ./example
