name: Publish expo-horizon-location to NPM
on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        options: [stable, nightly, rc]
      dry-run:
        type: boolean
        default: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow registered on main!"
